enum ErrorCode {
  AffiliateIdInvalid = 'AFFILIATE_ID_INVALID',
  AffiliateIdRequired = 'AFFILIATE_ID_REQUIRED',
  InviteCodeTaken = 'INVITE_CODE_TAKEN',
  InviteCodeInvalid = 'INVITE_CODE_INVALID',
  InviteCodeRequired = 'INVITE_CODE_REQUIRED',
  EmailInUse = 'EMAIL_IN_USE',
  EmailInvalid = 'EMAIL_INVALID',
  EmailRequired = 'EMAIL_REQUIRED',
  IdRequired = 'ID_REQUIRED',
  IdInvalid = 'ID_INVALID',
  NameInvalid = 'NAME_INVALID',
  NameRequired = 'NAME_REQUIRED',
  PasswordInvalid = 'PASSWORD_INVALID',
  PasswordRequired = 'PASSWORD_REQUIRED',
  PlanIdInvalid = 'PLAN_ID_INVALID',
  PlanIdRequired = 'PLAN_ID_REQUIRED',
  OrganizationIdInvalid = 'ORGANIZATION_ID_INVALID',
  OrganizationIdRequired = 'ORGANIZATION_ID_REQUIRED',
  RolesInvalid = 'ROLES_INVALID',
  RolesRequired = 'ROLES_REQUIRED',
  UserIdInvalid = 'USER_ID_INVALID',
  UserIdRequired = 'USER_ID_REQUIRED',
}

export default ErrorCode;
